#!/bin/bash -eu

cd $(dirname $0)/..

trap "docker-compose down --volume" 0
docker volume create --name gradle-cache >/dev/null
docker volume create --name test-results >/dev/null

docker-compose run --rm --service-ports dev "${@-bash}"
